project:
  type: website
  output-dir: _site

bibliography: references.bib

website:
  title: "Knowledge Base"

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Epidemiology"
        href: epidemiology/index.qmd
      - text: "Positron"
        href: positron/index.qmd
      - text: "Python"
        href: python/index.qmd
      - text: "R"
        href: r/index.qmd
      - text: "General"
        href: general/index.qmd
      - href: psychology-psychiatry/index.qmd
        text: Psychology & Psychiatry

    tools:
      - icon: github
        href: https://nhazkal.github.io/knowledge-base/

  search: true
  page-navigation: true

format:
  html:
    citeproc: true
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap